# Generated by Django 5.0 on 2023-12-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_weeklyevaluation_coach_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='coach_feedback',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='player_feedback',
        ),
    ]
