# Generated by Django 5.0 on 2023-12-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_remove_weeklyevaluation_coach_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyevaluation',
            name='coach_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='player_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
