# Generated by Django 5.0 on 2023-12-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_weeklyevaluation_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
