# Generated by Django 5.0 on 2023-12-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_alter_weeklyevaluation_options_commonevaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonEvaluation',
        ),
    ]
