# Generated by Django 5.0 on 2023-12-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_commonevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonevaluation',
            name='best_shot',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='best_shot_for_winner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='long_term_goal_competition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='long_term_goal_physical',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='long_term_goal_tactical',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='long_term_goal_technical',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='short_term_goal_competition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='short_term_goal_physical',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='short_term_goal_tactical',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='short_term_goal_technical',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='shot_improved',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
