# Generated by Django 5.0 on 2023-12-19 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_alter_commonevaluation_best_shot_and_more'),
        ('users', '0016_delete_weeklyevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvaluation',
            fields=[
                ('matchtype', models.CharField(choices=[('S', 'Спаринг'), ('T', 'Турнир')], default='S', max_length=10)),
                ('tournament', models.CharField(blank=True, max_length=200, null=True)),
                ('round', models.CharField(choices=[('Q1', 'Квалификация 1 кръг'), ('Q2', 'Квалификация 2 кръг'), ('Q1', 'Квалификация 3 кръг'), ('R1', '1 кръг'), ('R2', '2 кръг'), ('R3', '3 кръг'), ('QF', 'Четвъртфинал'), ('SF', 'Полуфинал'), ('F', 'Финал'), ('NO', 'Няма')], default='NO', max_length=10)),
                ('opponent', models.CharField(blank=True, max_length=200, null=True)),
                ('winloose', models.CharField(choices=[('W', 'Победа'), ('L', 'Загуба')], default='W', max_length=10)),
                ('result', models.CharField(max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('coachVisible', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
            options={
                'ordering': ['player__name', '-created'],
            },
        ),
    ]
