# Generated by Django 5.0 on 2023-12-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_matchevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevaluation',
            name='coachVisible',
            field=models.BooleanField(default=False),
        ),
    ]
