# Generated by Django 5.0 on 2023-12-20 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_alter_matchevaluation_coachvisible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevaluation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
