# Generated by Django 5.0 on 2023-12-20 18:52

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_alter_matchevaluation_coachvisible_and_more'),
        ('users', '0017_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEvaluation',
            fields=[
                ('date', models.DateField(default=datetime.datetime.today, null=True)),
                ('practicetype', models.CharField(choices=[('S', 'Индивидуална'), ('G', 'Групова')], default='G', max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('coachVisible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coachdaily', to='users.profile')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerdaily', to='users.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
