# Generated by Django 5.0 on 2023-12-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_dailyevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyevaluation',
            name='mark',
            field=models.IntegerField(choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='agility',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='attack',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='base_line',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='break_rhythm',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='concentration',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='condition',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='confidence',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='defence',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='delay',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='effort',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='endurance',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='error_handling',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='mental',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='mental_stabillity',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='net',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='pleasure',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_backhand',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_backhand_lob',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_backhand_passing_shot',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_backhand_slice',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_backhand_topspin',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_backhand_volley',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_drop_shot',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_first_serve',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_forehand',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_forehand_lob',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_forehand_passing_shot',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_forehand_slice',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_forehand_topspin',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_forehand_volley',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_receive_first_serve',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_receive_second_serve',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_second_serve',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='quality_smash',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='receiving',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='sence',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='serve',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='skill',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='speed',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='speedup',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='strength',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='style_change',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='tactical',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commonevaluation',
            name='technical',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='coach_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='coach_discipline',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='coach_effort',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='coach_motivation',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='coach_understanding',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='player_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='player_discipline',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='player_effort',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='player_motivation',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='player_understanding',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
