# Generated by Django 5.0 on 2023-12-22 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0016_dailyevaluation_mark_alter_commonevaluation_agility_and_more'),
        ('users', '0017_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='coach_concentration',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='coach_discipline',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='coach_effort',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='coach_feedback',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='coach_motivation',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='coach_understanding',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='player_concentration',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='player_discipline',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='player_effort',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='player_feedback',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='player_motivation',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='player_understanding',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='topic',
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='average',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='fri_concentration',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='fri_diet',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='fri_practice',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='fri_recovery',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='fri_sleep',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='mon_concentration',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='mon_diet',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='mon_practice',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='mon_recovery',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='mon_sleep',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='sat_concentration',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='sat_diet',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='sat_practice',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='sat_recovery',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='sat_sleep',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='sun_concentration',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='sun_diet',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='sun_practice',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='sun_recovery',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='sun_sleep',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='thu_concentration',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='thu_diet',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='thu_practice',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='thu_recovery',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='thu_sleep',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='tue_concentration',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='tue_diet',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='tue_practice',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='tue_recovery',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='tue_sleep',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='wed_concentration',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='wed_diet',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='wed_practice',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='wed_recovery',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='wed_sleep',
            field=models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coachconditioning', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerconditioning', to='users.profile'),
        ),
    ]
