# Generated by Django 5.0 on 2023-12-22 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0017_remove_weeklyevaluation_coach_concentration_and_more'),
        ('users', '0017_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='average',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='fri_concentration',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='fri_diet',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='fri_practice',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='fri_recovery',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='fri_sleep',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='mon_concentration',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='mon_diet',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='mon_practice',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='mon_recovery',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='mon_sleep',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='sat_concentration',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='sat_diet',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='sat_practice',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='sat_recovery',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='sat_sleep',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='sun_concentration',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='sun_diet',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='sun_practice',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='sun_recovery',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='sun_sleep',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='thu_concentration',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='thu_diet',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='thu_practice',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='thu_recovery',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='thu_sleep',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='tue_concentration',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='tue_diet',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='tue_practice',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='tue_recovery',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='tue_sleep',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='wed_concentration',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='wed_diet',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='wed_practice',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='wed_recovery',
        ),
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='wed_sleep',
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='coach_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='coach_discipline',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='coach_effort',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='coach_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='coach_motivation',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='coach_understanding',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='player_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='player_discipline',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='player_effort',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='player_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='player_motivation',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='player_understanding',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='weeklyevaluation',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='users.profile'),
        ),
        migrations.CreateModel(
            name='ConditioningEvaluation',
            fields=[
                ('year', models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032)], default=2023)),
                ('week', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57)], default=51)),
                ('mon_practice', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('mon_concentration', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('mon_sleep', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('mon_diet', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('mon_recovery', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('tue_practice', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('tue_concentration', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('tue_sleep', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('tue_diet', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('tue_recovery', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('wed_practice', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('wed_concentration', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('wed_sleep', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('wed_diet', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('wed_recovery', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('thu_practice', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('thu_concentration', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('thu_sleep', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('thu_diet', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('thu_recovery', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('fri_practice', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('fri_concentration', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('fri_sleep', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('fri_diet', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('fri_recovery', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sat_practice', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sat_concentration', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sat_sleep', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sat_diet', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sat_recovery', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sun_practice', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sun_concentration', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sun_sleep', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sun_diet', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sun_recovery', models.IntegerField(blank=True, choices=[('', '--'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('average', models.FloatField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coachconditioning', to='users.profile')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerconditioning', to='users.profile')),
            ],
            options={
                'ordering': ['player__name', '-year', '-week'],
            },
        ),
    ]
