# Generated by Django 5.0 on 2023-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0018_remove_weeklyevaluation_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='fri_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='fri_diet',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='fri_practice',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='fri_recovery',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='fri_sleep',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='mon_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='mon_diet',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='mon_practice',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='mon_recovery',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='mon_sleep',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='sat_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='sat_diet',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='sat_practice',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='sat_recovery',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='sat_sleep',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='sun_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='sun_diet',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='sun_practice',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='sun_recovery',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='sun_sleep',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='thu_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='thu_diet',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='thu_practice',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='thu_recovery',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='thu_sleep',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='tue_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='tue_diet',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='tue_practice',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='tue_recovery',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='tue_sleep',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='wed_concentration',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='wed_diet',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='wed_practice',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='wed_recovery',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='conditioningevaluation',
            name='wed_sleep',
            field=models.IntegerField(blank=True, choices=[('', '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
