# Generated by Django 5.0 on 2023-12-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0020_alter_conditioningevaluation_week_and_more'),
        ('users', '0020_remove_messages_recepient_messages_recipient_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyevaluation',
            unique_together={('player', 'week', 'year')},
        ),
    ]
