# Generated by Django 5.0 on 2023-12-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0021_alter_weeklyevaluation_unique_together'),
        ('users', '0020_remove_messages_recepient_messages_recipient_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conditioningevaluation',
            unique_together={('player', 'week', 'year')},
        ),
    ]
