# Generated by Django 5.0 on 2023-12-30 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0022_alter_conditioningevaluation_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyevaluation',
            options={'ordering': ['-date', '-created']},
        ),
    ]
