# Generated by Django 5.0 on 2023-12-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hand',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='R', max_length=10),
        ),
    ]
