# Generated by Django 5.0 on 2023-12-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backhand',
            field=models.CharField(choices=[('S', 'Single handed'), ('S', 'Double handed')], default='D', max_length=10),
        ),
    ]
