# Generated by Django 5.0 on 2023-12-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_backhand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backhand',
            field=models.CharField(choices=[('S', 'Single handed'), ('D', 'Double handed')], default='D', max_length=10),
        ),
    ]
