# Generated by Django 5.0 on 2023-12-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_backhand'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_motivation', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('coach_motivation', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to='users.profile')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='users.profile')),
            ],
        ),
    ]
