# Generated by Django 5.0 on 2023-12-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_weeklyevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyevaluation',
            name='coach',
        ),
    ]
