# Generated by Django 5.0 on 2023-12-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_weeklyevaluation_created_alter_weeklyevaluation_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyEvaluation',
        ),
    ]
