# Generated by Django 5.0 on 2023-12-17 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_weeklyevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyEvaluation',
            fields=[
                ('player_motivation', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('coach_motivation', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='users.profile')),
            ],
        ),
    ]
