# Generated by Django 5.0 on 2023-12-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_weeklyevaluation_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyevaluation',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='coach_motivation',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='weeklyevaluation',
            name='player_motivation',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
