# Generated by Django 5.0 on 2023-12-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_weeklyevaluation_topic_alter_weeklyevaluation_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backhand',
            field=models.CharField(choices=[('S', 'С една ръка'), ('D', 'С две ръце')], default='D', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hand',
            field=models.CharField(choices=[('L', 'Лява'), ('R', 'Дясна')], default='R', max_length=10),
        ),
    ]
