# Generated by Django 5.0 on 2023-12-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_backhand_alter_profile_hand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyEvaluation',
        ),
    ]
