# Generated by Django 5.0 on 2023-12-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_delete_weeklyevaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
    ]
