# Generated by Django 5.0 on 2023-12-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linked_email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
