# Generated by Django 5.0 on 2023-12-29 14:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_messages_recepient_messages_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(null=True, upload_to='profiles/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['player__name'],
            },
        ),
    ]
