# Generated by Django 5.0 on 2023-12-29 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_playerotw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerotw',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
