# Generated by Django 5.0 on 2023-12-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='body',
        ),
    ]
