# Generated by Django 5.0 on 2023-12-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_description_news_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='news/default.jpg', null=True, upload_to=''),
        ),
    ]
