# Generated by Django 5.0 on 2024-01-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProgramImage',
        ),
    ]
