# Generated by Django 5.0 on 2024-01-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_rename_image_programimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='author',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title',
        ),
    ]
