# Generated by Django 5.0 on 2024-01-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_remove_program_author_remove_program_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, default='programs/default.jpg', null=True, upload_to='programs'),
        ),
    ]
