# Generated by Django 5.0 on 2024-01-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_program_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='programs'),
        ),
    ]
